FROM golang:1.21-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Enable Go modules
ENV GO111MODULE=on

# Enable Go debug output
ENV GODEBUG=netdns=cgo

# Run with debug output
CMD ["sh", "-c", "ls -la && pwd && go run -v cmd/api/main.go"] 