apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: db-migration
        image: postgres:15
        command: ["psql"]
        args:
          - "-h"
          - "cloudsql-proxy"
          - "-U"
          - "fowergram_user"
          - "-d"
          - "fowergram_prod"
          - "-f"
          - "/migrations/000001_create_users_table.up.sql"
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: fowergram-secrets
                key: db-password
        volumeMounts:
          - name: migration-script
            mountPath: /migrations
      volumes:
        - name: migration-script
          configMap:
            name: db-migration
      restartPolicy: Never
  backoffLimit: 4 