apiVersion: apps/v1
kind: Deployment
metadata:
  name: fowergram-api
  labels:
    app: fowergram-api # เพิ่ม labels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fowergram-api
  template:
    metadata:
      labels:
        app: fowergram-api
    spec:
      containers:
        - name: fowergram-api
          image: asia-southeast1-docker.pkg.dev/fowergram-backend/fowergram-repo/api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: fowergram-secrets
                  key: db-host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: fowergram-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fowergram-secrets
                  key: db-password
            - name: DB_NAME # เพิ่ม DB_NAME
              valueFrom:
                secretKeyRef:
                  name: fowergram-secrets
                  key: db-name
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe: # เพิ่ม health check
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
