apiVersion: v1
kind: Service
metadata:
  name: fowergram-api
  labels:
    app: fowergram-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: fowergram-api
